; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "minecraft mod eastinstaller"
!define PRODUCT_VERSION "1.0"
!define PRODUCT_PUBLISHER "devbinx"

SetCompressor lzma

; MUI 1.67 compatible ------
!include "MUI.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "${NSISDIR}\Contrib\Graphics\Icons\modern-install.ico"

; Welcome page
!insertmacro MUI_PAGE_WELCOME
; Components page
!insertmacro MUI_PAGE_COMPONENTS
; Directory page
!insertmacro MUI_PAGE_DIRECTORY
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
!insertmacro MUI_PAGE_FINISH

; Language files
!insertmacro MUI_LANGUAGE "Korean"

; Reserve files
!insertmacro MUI_RESERVEFILE_INSTALLOPTIONS

; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "mc_1.20.1.exe"
InstallDir "C:\Users\USER\AppData\Roaming\.minecraft\mods"
ShowInstDetails show

Section "AmbientSounds" SEC01
  SetOutPath "C:\Users\USER\AppData\Roaming\.minecraft\mods"
  SetOverwrite ifnewer
  File "..\Downloads\1.20.1_mods\mods\AmbientSounds_FABRIC_v5.2.22_mc1.20.1.jar"
SectionEnd

Section "artifacts" SEC02
  File "..\Downloads\1.20.1_mods\mods\artifacts-fabric-9.2.0.jar"
SectionEnd

Section "blur" SEC03
  File "..\Downloads\1.20.1_mods\mods\blur-3.1.0.jar"
SectionEnd

Section "charmofundying" SEC04
  File "..\Downloads\1.20.1_mods\mods\charmofundying-fabric-6.4.5+1.20.1.jar"
SectionEnd

Section "geophilic" SEC05
  File "..\Downloads\1.20.1_mods\mods\geophilic-v2.0.0-mc1.20u1.20.1.jar"
SectionEnd

Section "icarus" SEC06
  File "..\Downloads\1.20.1_mods\mods\icarus-1.16.jar"
SectionEnd

Section "jei" SEC07
  File "..\Downloads\1.20.1_mods\mods\jei-1.20.1-fabric-15.2.0.27.jar"
SectionEnd

Section "journymap" SEC08
  File "..\Downloads\1.20.1_mods\mods\journeymap-1.20.1-5.9.18-fabric.jar"
SectionEnd

Section "MouseTweaks" SEC09
  File "..\Downloads\1.20.1_mods\mods\MouseTweaks-fabric-mc1.20-2.25.jar"
SectionEnd

Section "notenoughanimations" SEC10
  File "..\Downloads\1.20.1_mods\mods\notenoughanimations-fabric-1.6.4-mc1.20.jar"
SectionEnd

Section "PresenceFootsteps" SEC11
  File "..\Downloads\1.20.1_mods\mods\PresenceFootsteps-1.9.0.jar"
SectionEnd

Section "SimpleAnimatedGuns" SEC12
  File "..\Downloads\1.20.1_mods\mods\SimpleAnimatedGuns-1.20.1-v1.3-BETA-2.jar"
SectionEnd

Section "TownsandTowers" SEC13
  File "..\Downloads\1.20.1_mods\mods\Towns-and-Towers-1.11-Fabric+Forge.jar"
SectionEnd

Section "travelersbackpack" SEC14
  File "..\Downloads\1.20.1_mods\mods\travelers-backpack-1.20.1-9.1.8.jar"
SectionEnd

Section "trinkets" SEC15
  File "..\Downloads\1.20.1_mods\mods\trinkets-3.7.1.jar"
SectionEnd

Section "waystone" SEC16
  File "..\Downloads\1.20.1_mods\mods\waystones-fabric-1.20-14.0.2.jar"
SectionEnd

Section "library" SEC17
  File "..\Downloads\1.20.1_mods\mods\architectury-9.1.12-fabric.jar"
  File "..\Downloads\1.20.1_mods\mods\balm-fabric-1.20.1-7.1.4.jar"
  File "..\Downloads\1.20.1_mods\mods\azurelib-fabric-1.20.1-2.0.6.jar"
  File "..\Downloads\1.20.1_mods\mods\fabric-language-kotlin-1.10.10+kotlin.1.9.10.jar"
  File "..\Downloads\1.20.1_mods\mods\fabric-api-0.90.7+1.20.1.jar"
  File "..\Downloads\1.20.1_mods\mods\cristellib-1.1.5-fabric.jar"
  File "..\Downloads\1.20.1_mods\mods\CreativeCore_FABRIC_v2.11.10_mc1.20.1.jar"
  File "..\Downloads\1.20.1_mods\mods\cloth-config-11.1.106-fabric.jar"
  File "..\Downloads\1.20.1_mods\mods\geckolib-fabric-1.20.1-4.2.4.jar"
  File "..\Downloads\1.20.1_mods\mods\midnightlib-fabric-1.4.1.jar"
  File "..\Downloads\1.20.1_mods\mods\Zoomify-2.11.2.jar"
  File "..\Downloads\1.20.1_mods\mods\youre-in-grave-danger-2.0.0-beta.3.jar"
  File "..\Downloads\1.20.1_mods\mods\yet-another-config-lib-fabric-3.2.1+1.20.jar"
SectionEnd

Section -Post
SectionEnd

; Section descriptions
!insertmacro MUI_FUNCTION_DESCRIPTION_BEGIN
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC01} "�������� ȯ����"
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC02} "�پ��� ���� �߰�"
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC03} "�κ��丮 & �Ͻ����� â�϶� ��� ����ó��"
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC04} "�һ��� ���� ��ű��� ���� ����"
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC05} "���� ���̿� ����"
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC06} "�پ��� ���� �߰�"
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC07} "���չ� ��ƺ���"
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC08} "�̴ϸ�"
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC09} "������ �ű� �� ���콺 ���� ����"
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC10} "�پ��� �ִϸ��̼� �߰�"
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC11} "�߼Ҹ� ����"
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC12} "�Ѹ��"
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC13} "�� ������ �پ��� Ÿ�� & ���� �߰�"
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC14} "���� �߰�"
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC15} "���� & ���� & �һ��� ���� ��� ��ű� ���� �߰�"
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC16} "Ȱ��ȭ�� ���ۼ����� �����̵� �� �� �ִ� ���ۼ� �߰�"
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC17} "��� ���̺귯�� �� dependencies"
!insertmacro MUI_FUNCTION_DESCRIPTION_END